apiVersion: v1 # K8s api version, 특정 object는 v1beta를 사용한다.
kind: Pod      # 생성할 object, controller의 종류
metadata:      
  name: hanium-node   # object의 고유 이름, 복수로 생성할 경우 prefix로 사용된다.
  labels:            # 외부에서 Pod을 찾을 때 사용할 label. 복수의 label 입력가능
    service-name: hanium-node
spec:                # 기대되는 obejct의 상태
  containers:        # Pod 내부에서 생성할 컨테이너 목록
  - name: hanium-node # 컨테이너 이름
    image: sds111888/docker-node-express-mongoapp # 컨테이너를 실행할 이미지
    readinessProbe: 
      httpGet:       # health check 방법 exec, httpGet, tcpSocket
        path: /      # health check path
        port: 8080   # health check port
    livenessProbe:
      httpGet:
        path: /
        port: 8080

apiVersion: v1
kind: Service
metadata:
  name: hanium-node
spec:
  type: LoadBalancer # 외부에 Pod을 어떤 형태로 노출할지 결정
  ports:
  - port: 8080       # 외부에 노출할 포트
    targetPort: 8080 # 컨테이너의 포트
  selector:
    service-name: hanium-node # Service가 연결할 대상 Pod의 label
